version: "3.2"
services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
        - ./db:/backup
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: <YourStrong!Passw0rd>
    ports:
        - 1433:1433